# Generated by Django 5.0.1 on 2024-01-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipeproduct_recipe_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeproduct',
            options={'ordering': ['id'], 'verbose_name': 'Продукт в рецепте', 'verbose_name_plural': 'Продукты в рецептах'},
        ),
    ]
