# Generated by Django 5.0.1 on 2024-01-28 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('recipe', '0004_remove_recipe_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='products',
            field=models.ManyToManyField(through='recipe.RecipeProduct', to='product.product'),
        ),
        migrations.AlterField(
            model_name='recipeproduct',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe'),
        ),
    ]
